### PR TITLE
Add Modular Transmit/Receive Behavior to SimCan

### PR DESCRIPTION
**Pull request by cosparks**
Created CanBehavior classes so that we can easily define the transmitting and receiving behavior of a SimCan object without having to define new classes.  The SimCan constructor now takes CanBehavior* as param, which defines transmit and receive methods.

- Adds CanUrbanAccessoriesBehavior which transmits can messages with pseudo-random data and dataLength (most messages have a valid can status ID but some do not)  
- Adds CanBmsBehavior--refactored from SimCan (I didn't make any changes to data or functionality here)

### CODE REVIEW

**Comment by silviu-toderita** [comment]
This is looking really good and I like the modularity. Can we take it a step further and include some common stuff in the SimCan class? For example, why not handle the transmission of a bunch of CAN messages from SimCan? The "transmit" method of each CanBehavior class could return a vector of CAN messages to send out. It would be less code repetition.

**Comment by cosparks** [comment]
That's a good idea, the serial printing code could probably be put into static methods in SimCan too.  Is there a reason that serial is passed in as a pointer to SimCan?  Not sure if it's expensive to grab the Serial object a bunch at runtime, but getting rid of it as a member would make it so I could define some of the serial output behavior in static methods and avoid having a mutual reference between SimCan and CanBehavior classes

**Comment by silviu-toderita** [comment]
> That's a good idea, the serial printing code could probably be put into static methods in SimCan too. Is there a reason that serial is passed in as a pointer to SimCan? Not sure if it's expensive to grab the Serial object a bunch at runtime, but getting rid of it as a member would make it so I could define some of the serial output behavior in static methods and avoid having a mutual reference between SimCan and CanBehavior classes

To be honest I don't remember exactly why I did that, so feel free to change it!

**Comment by silviu-toderita** [comment]
Just had a look at your latest commit, looking good. Can we make a function like "sendCan" in SimCan class that we just pass a CanMessage to and the SimCan class can take care of transmitting?  That way the "CanBehavior" classes don't actually have to do any of the CAN communication, and can just specify behaviour. And maybe something similar for receiving messages? Although that part would be more complex. Not sure how much you want to get into this, as this part of the project isn't too important.

**Comment by cosparks** [comment]
Hey yep!  I started refactoring that today, but am super tired so I think I'll finish it tomorrow

**Comment by silviu-toderita** [comment]
> Hey yep! I started refactoring that today, but am super tired so I think I'll finish it tomorrow

Oh cool, I didn't realize it's still a WIP. Let me know when it's done

**Comment by cosparks** [comment]
Done if you want to take a look

**Pull request merged**
